### ISSUE TITLE
Black screen on win32

### ISSUE THREAD

**Issue by Sand3r-** [ryanfleury/fight#1]
Hi, along with a friend, we've tried running the game on windows, however all we see is a black screen.

**Comment by princessakokosowa** [comment]
Well, that's true.

**Comment by ryanfleury** [comment]
I think that is just the missing title screen we never actually added; this was an unfinished game we threw together in 12 hours or something like that. You can exit the title screen by pressing Enter.

Warning, pretty sure the sound code is super busted :)

**Comment by Sand3r-** [comment]
Wow, thanks for such a fast response. I have figured out the exiting title screen trick through the debugger, but even afterwards nothing is actually rendered, although admittedly the sound is there 😄. I really appreciate the code quality kept here, esp. given amount of time you guys actually spent on this.
